[package]
name = "torytis"
version = "1.5.8"
edition = "2021"

[dependencies]
axum = "0.8.1"
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
encoding_rs = "0.8.35"
glob = "0.3.2"
html5ever = "0.30.0"
include_dir = { version = "0.7.4", features = ["glob"] }
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["fs"] }
version-compare = "0.2.0"
xmltree = "0.11.0"
html_regex = { path = "../html_regex"}
consts = { path = "../consts" }
downloader = { path = "../downloader" }
flater = { path = "../flater" }
file_manager = { path = "../file_manager" }
commander = { path = "../commander" }
serde_qs = "0.14.0"
openssl = { version = "0.10", features = ["vendored"] }