[package]
name = "torytis"
version = "1.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.4.17", features = ["derive"] }
glob = "0.3.1"
include_dir = { version = "0.7.3", features = ["glob"] }
regex = "1.10.2"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
version-compare = "0.1.1"
xmltree = "0.10.3"
