[workspace]
resolver = "2"

members = [
  "./src/packages/html_regex",
  "./src/packages/torytis",
  "./src/packages/consts",
  "./src/packages/downloader",
  "./src/packages/flater",
  "./src/packages/file_manager"
]

[package]
name = "torytis-monorepo"
version = "0.0.1"
edition = "2021"

