[package]
name = "downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []

[dependencies]
tokio = { version = "1.40.0", features = [ "fs", "rt-multi-thread", "macros"] }
reqwest = { version = "0.12.8", features = ["rustls-tls"] }
